{{- if and .Values.serviceAccount.create .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-quota-watch.serviceAccountName" . }}
  labels:
    {{- include "kube-quota-watch.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
